# Generated by Django 4.1.7 on 2023-03-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='zop_number',
            new_name='zip_number',
        ),
    ]
